project:
  type: website
  pre-render:
    - R/cleanup.R
    - R/fetch.R
    - R/setup.R
    - R/setup_champ.R
  post-render:
    - R/finish.R

title-block-banner: "images/maley_banner.jpg"
title-block-banner-color: "white"

website:
  title: "CD Le Maley 2023"
  navbar:
    background: "#00513a"
    left:
      - href: index.qmd
        text: Accueil
      - href: actuel/Carre_A.qmd
      - href: actuel/Carre_B.qmd
  page-footer:
    left:
      - text: "EquiEvents"
    right: 
      - text: "info@equievents.ch"
        href: "mailto:info@equievents.ch"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    lang: fr
    execute:
      echo: false
      warning: false

editor: visual

